#-------------------
# --- Spabreaks ---
#-------------------
[[session]]
name = "spabreaks"
path = "~/code/spabreaks/spabreaks/"
startup_command = "_tmux_git-repo"

[[session]]
name = "spabreaks-dev"
path = "~/code/spabreaks/spabreaks/"
startup_command = "_tmux_spabreaks_spabreaks_dev"

[[session]]
name = "spabreaks-console"
path = "~/code/spabreaks/spabreaks/"
startup_command = "make console"

[[session]]
name = "spabreaks-cypress"
path = "~/code/spabreaks/spabreaks/"
startup_command = "task cypress:build-and-up"

[[session]]
name = "spabreaks-guard"
path = "~/code/spabreaks/spabreaks/"
startup_command = "make guard"

[[session]]
name = "spabreaks-psql"
path = "~/code/spabreaks/spabreaks/"
startup_command = "make psql"

[[session]]
name = "spabreaks-env"
path = "~/code/spabreaks-env"
startup_command = "_tmux_git-repo"

#-------------------
#   --- blog ---
#-------------------
[[session]]
name = "blog"
path = "~/code/spabreaks/blog/"
startup_command = "_tmux_git-repo"

[[session]]
name = "blog-dev"
path = "~/code/spabreaks/blog/"
startup_command = "_tmux_spabreaks_blog_dev"

#-------------------
#   --- sales ---
#-------------------
[[session]]
name = "sales"
path = "~/code/spabreaks/sales/"
startup_command = "_tmux_git-repo"

[[session]]
name = "sales-dev"
path = "~/code/spabreaks/sales/"
startup_command = "_tmux_spabreaks_sales_dev"

#-------------------
#  --- wss-data ---
#-------------------
[[session]]
name = "wss-data"
path = "~/code/spabreaks/wss-data/"
startup_command = "_tmux_git-repo"

[[session]]
name = "wss-data-dev"
path = "~/code/spabreaks/wss-data/"
startup_command = "_tmux_spabreaks_wss_data_dev"

#-------------------
# --- my-account ---
#-------------------
[[session]]
name = "my-account"
path = "~/code/spabreaks/my-account/"
startup_command = "_tmux_git-repo"

[[session]]
name = "my-account-dev"
path = "~/code/spabreaks/my-account/"
startup_command = "_tmux_spabreaks_my_account_dev"

#-------------------
#    --- VRS ---
#-------------------
[[session]]
name = "vrs"
path = "~/code/spabreaks/voucher-portal/"
startup_command = "_tmux_git-repo"

[[session]]
name = "vrs-dev"
path = "~/code/spabreaks/voucher-portal/"
startup_command = "_tmux_spabreaks_vrs_dev"

[[session]]
name = "vrs-psql"
path = "~/code/spabreaks/voucher-portal/"
startup_command = "make psql"

#-------------------
#  --- Config ---
#-------------------

[[session]]
name = "dotfiles"
path = "~/dotfiles"
startup_command = "_tmux_git-repo"

[[session]]
name = "nix-config"
path = "~/nix-config"
startup_command = "_tmux_git-repo"

[[session]]
name = "config-opencode"
path = "~/.config/opencode/"
startup_command = "_tmux_git-repo"

#-------------------
#   --- Repos ---
#-------------------

[[session]]
name = "mem"
path = "~/code/palekiwi-labs/mem"
startup_command = "_tmux_git-repo"

[[session]]
name = "ocx"
path = "~/code/palekiwi-labs/ocx"
startup_command = "_tmux_git-repo"

[[session]]
name = "notes-pl"
path = "~/Nextcloud-pl/Notes"
startup_command = "_tmux_git-repo"

[[session]]
name = "notes-sb"
path = "~/Nextcloud-sb/Notes"
startup_command = "_tmux_git-repo"

[[session]]
name = "ff_monads"
path = "~/code/spabreaks/ff_monads/"
startup_command = "_tmux_git-repo"

[[session]]
name = "rails-utils.nvim"
path = "~/code/neovim/plugins/rails-utils.nvim"
startup_command = "_tmux_git-repo"

[[session]]
name = "rspec-runner"
path = "~/code/neovim/plugins/rspec-runner.nvim"
startup_command = "_tmux_git-repo"

[[session]]
name = "homelab"
path = "~/code/homelab"
startup_command = "_tmux_git-repo"

#-------------------
#    --- ssh ----
#-------------------

[[session]]
name = "haze"
startup_command = "ssh haze -A"

[[session]]
name = "kyomu"
startup_command = "ssh kyomu -A"

#-------------------
#   --- tools ----
#-------------------

[[session]]
name = "taskwarrior"
startup_command = "taskwarrior-tui"

#-------------------
#  --- default ---
#-------------------

[default_session]
startup_command = "_tmux_git-repo"
